appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: G6iJUiaY6h4vqJY9sl4qOf7ReluuRlvQ9O21I1DBNlp+mD/qTHxbamt2Tbg+dUOH6GBCe9u1DkhxlVfhF/v1qUIODCOZsPUekABUAUhLMcJDxbO5dYCJLy/Jcl0JSDNLZsnc2/9uBnV0vMINXPk3wfWlsq+ahf/1uaYfi4fapuER1S1heESja41d8zmf/A8RRJ+v7MtWHywdHBHkmfhAzY2hAz9PQ/24/2HXyWLhVCWL2PGU/4h+x1ooKB/M30BtrDCyxCJqS3VJdbb201hpHghKZZC6/EMr1m+xAn21mPQpxRQTDVLvJFrLSHgrIfzBUGnWFE9g1L5CkYjpbfMQ+TC6g0KmFx5gM3em0+th89igEQPMFCfJ0X3VDMsIifqd+tuQlVP6NkeQZnP8UQxN26gYMOsbwGmGFNuvoVd9KjsZ+li/EQ4Qq9B2zVuOSFdqYDRODPROm3z3xTKrqBY89oe3IB/EDZqcmnNxreUC+DY6yW4bbN5ft8ijIGyD0YS5KkgJC+/PpNO4bOXz9SdoNwu8OIaK/bCmK92CFTmGAEGZKqDW//lCTAKZ2jyF5HUu0IKh/Hgs+UbqFMvKY/dnGLvMr8LMHQGqS3wSMMx/kLIMT89Va2XOL+hdP4cnkGj9LEQhPnVYUay672IgbccB1/PhHIWLoR/A7913YSN/z+s=}
provider:
  win: azure
