travis:
  secure:
    BINSTAR_TOKEN: CUCB3f2YS0dJHyStdaV4SCyJwWIJ/4HPhphNXB+vdtbt3ur7DCoQg1s/Kfr1cKcLGYpfnJCqt04xRboSkttRfM8IyXYJXGyyY2aBSPNkQ74eFbTz4SdjW91V/ANe3XcD36up7qxgO8HLVdU64+fJPd76WmKUVTzUCE7ekoN0PfY8wUqlwmiMjS8OcjRNmdw4fAd/9TbB7wEMUwlr4fG9OsG9Kk6CWNZRanuHfEZw+9MVP7FqOcVfB4E/D72J+uPewTKR/FYL74YaiXHbwu+Nwp8i8If9nZJt3l4Jt0KFnFqW5ISnJ7MKsjmrtD5xQwoODt9gsPmCXwoF2ARHvvrkkAVC2RsD2yNtQJBzE4mydMex4XYmhXTtBnPK8vFCGBFCyN2fyUBUtpapv3w8VpQggs56UdFq+AgqIbcC0dnWKKc6/1ph7C5orOH+AklMfbnYPdNyBTolsqnepWEEdRUNyygfTfSGMNKGomqweQBXUCqGhHeDxiv/ypeaQ+rS7mIB+6LYMfYEbyOJDRvr0GimAMkM1vldXIRyZ2AuX+Y9NxyoMstuqsRYs0ncfDJKeZoRb0C6o9GQ+py/bnyOrTZwt2FNxTCrqA/Q+VEDn/BcakZs/946XZfNq8WyypsWslHLhl42hnrGOTb/kwDMdcJEWAffcr1vGgHz50DgjJTpaag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
